/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fyp;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Harikrish
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public static final Pattern VALID_EMAIL_ADDRESS_REGEX = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
    public Register() {
        initComponents();
        this.setTitle("Sign Up");
        for(int i=1;i<=31;i++)
        {
            date.addItem(i);
        }
        for(int i=1960;i<=2015;i++)
        {
            year.addItem(i);
        }
        date.setSelectedIndex(-1);
        year.setSelectedIndex(-1);
        buttonGroup1.add(male);
        buttonGroup1.add(female);
        staff_year.setVisible(false);
        staff_label.setVisible(false);
        student_year.setVisible(false);
        student_label.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        email_id = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        retype_password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        country = new javax.swing.JComboBox();
        city = new javax.swing.JComboBox();
        college = new javax.swing.JComboBox();
        department = new javax.swing.JComboBox();
        register = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        branch = new javax.swing.JComboBox();
        student_label = new javax.swing.JLabel();
        student_year = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        roll_no = new javax.swing.JFormattedTextField();
        staff_label = new javax.swing.JLabel();
        staff_year = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        phone_no = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Roll No");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Email Id");

        jLabel5.setText("Password");

        jLabel6.setText("Retype Password");

        email_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                email_idKeyReleased(evt);
            }
        });

        retype_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                retype_passwordKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel7.setText("Sign Up");

        jLabel8.setText("Date of Birth");

        jLabel9.setText("Sex");

        jLabel10.setText("Country");

        jLabel11.setText("City");

        jLabel12.setText("College");

        jLabel13.setText("Department");

        date.setMaximumRowCount(31);

        month.setMaximumRowCount(12);
        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "Juky", "August", "October", "November", "December" }));
        month.setSelectedIndex(-1);

        year.setMaximumRowCount(500);
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        male.setText("Male");

        female.setText("Female");

        country.setMaximumRowCount(100);
        country.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a" }));
        country.setSelectedIndex(-1);

        city.setMaximumRowCount(100);
        city.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "c" }));
        city.setSelectedIndex(-1);

        college.setMaximumRowCount(500);
        college.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CEG", "MIT", "ACT", "SAP" }));
        college.setSelectedIndex(-1);

        department.setMaximumRowCount(500);
        department.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aeronautical Engineering", "Aerospace Engineering", "Agricultural & Irrigation Engineering", "Aircraft Maintenance Engineering", "Animation", "Apparel technology", "Applied electronics", "Applied Mathematics", "Architecture", "Automobile Engineering", "Avionics", "Bio Informatics", "Bio Medical Engineering", "Biotechnology", "Ceramic Technology", "Charted Accountancy", "Chemical Engineering", "Chemistry", "Civil Engineering", "Communication Systems", "Computer Science & Engineering", "Cryogenic Engineering", "Elecrical Engineering", "Electrical & Electronics Engineering", "Electronic media", "Electronics & Communication Engineering", "Electronics & Instrumentation", "Embedded Systems", "Energy Engineering", "Engineering Design", "Engineering Physics", "English Literature", "Finance", "Fluid Mechanics", "Food Technology", "Geo Informatics", "Harbour Engineering", "High Voltage Engineering", "Hospitality Administration", "HR", "Humanities & Social Sciences", "Industrial Engineering", "Information & Communications Technology", "Information Technology", "Internal Combustion Engineering", "Logistics", "M.Sc. CS-IT", "M.Sc. E-Media", "Manufacturing Engineering", "Marine Engineering", "Marketing", "Material Science", "Mathematics", "Mechanical Engineering", "Mechatronics", "Media Sciences", "Metallurgy", "Mining Engineering", "Nano Science and Technology", "Photonics", "Physics", "Printing Technology", "Production Engineering", "Remote Sensing", "Software Engineering", "Systems Engineering & Operations Research", "Technology Managment", "Telecommunication Engineering", "Textile Technology", "Theoretical Computer Science", "Thermal", "Transportation Engineering", "VLSI Design", "Other" }));
        department.setSelectedIndex(-1);

        register.setText("Sign Up");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jLabel14.setText("Branch");

        branch.setMaximumRowCount(100);
        branch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "B.E", "B.A", "B.Arch", "B.Com", "B.Sc", "B.Tech", "BBA", "BCA", "DEEE", "Diploma", "Dual Degree", "Intermediate", "M.A", "M.E", "M.Sc", "M.Sc(Integrated)", "M.Tech", "MBA", "MCA", "MS", "Ph.D", "Other" }));
        branch.setSelectedIndex(-1);

        student_label.setText("Year");

        student_year.setMaximumRowCount(5);
        student_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        student_year.setSelectedIndex(-1);

        jLabel16.setText("Type");

        type.setMaximumRowCount(10);
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "student", "staff" }));
        type.setSelectedIndex(-1);
        type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeItemStateChanged(evt);
            }
        });

        roll_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                roll_noKeyReleased(evt);
            }
        });

        staff_label.setText("Experience");

        jLabel15.setText("Phone No");

        phone_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phone_noKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(first_name)
                            .addComponent(last_name)
                            .addComponent(email_id)
                            .addComponent(password)
                            .addComponent(retype_password)
                            .addComponent(roll_no, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(register)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(male)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(female))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(country, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(city, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(college, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(branch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(student_label)
                                        .addComponent(staff_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(department, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(student_year, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(staff_year)
                                    .addComponent(phone_no))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(roll_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(male)
                    .addComponent(female)
                    .addComponent(jLabel16)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff_label)
                    .addComponent(staff_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(college, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(retype_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(register)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        String roll="",firstname="",lastname="",email="",pass="",pass1="",user_date="",user_month="",user_year="",user_sex="",phone="",experience="";
        String user_country="",user_city="",user_college="",user_branch="",user_department="",user_student_year="",user_type="",user_staff_year="";
        roll=roll_no.getText();
        firstname=first_name.getText();
        lastname=last_name.getText();
        email=email_id.getText();
        pass=new String(password.getPassword());
        pass1=new String(retype_password.getPassword());
        user_date=date.getSelectedItem().toString();
        user_month=month.getSelectedItem().toString();
        user_year=year.getSelectedItem().toString();
        if(male.isSelected())
        {
            user_sex=male.getText();
        }
        if(female.isSelected())
        {
            user_sex=female.getText();
        }
        user_country=country.getSelectedItem().toString();
        user_city=city.getSelectedItem().toString();
        user_college=college.getSelectedItem().toString();
        user_branch=branch.getSelectedItem().toString();
        user_department=department.getSelectedItem().toString();
        user_type=type.getSelectedItem().toString();
        user_student_year=student_year.getSelectedItem().toString();
        user_staff_year=staff_year.getText();
        phone=phone_no.getText();
        if(user_type=="student")
        {
            experience=user_student_year;
        }
        else
        {
            experience=user_staff_year;
        }
        DBConfig db=new DBConfig();
        int ret=db.insertNewUser(roll, firstname, lastname, email, pass,phone,user_date,user_month,user_year,user_sex,user_country, user_city, user_college, user_branch, user_department, user_type,experience);
        db=null;
        if(ret==1)
        {
            JOptionPane.showMessageDialog(this,"Email Id (or) roll no already exist!!!");
        }
        else if(ret==3)
        {
            JOptionPane.showMessageDialog(this,"Insertion Failed");
        }
        else if(ret==2)
        {
            JOptionPane.showMessageDialog(this,"Successfully Inserted!!");
            this.dispose();
            Login log=new Login();
            log.setVisible(true);
        }
    }//GEN-LAST:event_registerActionPerformed

    private void email_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_idKeyReleased
        // TODO add your handling code here:
        String email=email_id.getText();
        Matcher matcher = VALID_EMAIL_ADDRESS_REGEX .matcher(email);
        if(!matcher.find())
        {
            email_id.setForeground(Color.red);
        }
        else
        {
            email_id.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_email_idKeyReleased

    private void retype_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_retype_passwordKeyReleased
        // TODO add your handling code here:
        String pass=new String(password.getPassword());
        String pass1=new String(retype_password.getPassword());
        if(pass.equals(pass1))
        {
            retype_password.setForeground(Color.BLUE);
            password.setForeground(Color.BLUE);
        }
        else
        {
            retype_password.setForeground(Color.RED);
        }
    }//GEN-LAST:event_retype_passwordKeyReleased

    private void roll_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roll_noKeyReleased
        // TODO add your handling code here:
        String roll=roll_no.getText();
        Pattern pattern = Pattern.compile("[0-9]+");
        Matcher matcher = pattern.matcher(roll);
       if(!(matcher.find()))
       {
           roll_no.setForeground(Color.RED);
       }
       else
       {
           roll_no.setForeground(Color.BLUE);
       }
    }//GEN-LAST:event_roll_noKeyReleased

    private void typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeItemStateChanged
        // TODO add your handling code here:
        String name=type.getSelectedItem().toString();
        if(name=="student")
        {
            staff_year.setVisible(false);
            staff_label.setVisible(false);
            student_year.setVisible(true);
            student_label.setVisible(true);
        }
        else if(name=="staff")
        {
            student_year.setVisible(false);
            student_label.setVisible(false);
            staff_year.setVisible(true);
            staff_label.setVisible(true);
        }
    }//GEN-LAST:event_typeItemStateChanged

    private void phone_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_noKeyReleased
        // TODO add your handling code here:
        String phone=phone_no.getText();
        Pattern pattern = Pattern.compile("[0-9]+");
        Matcher matcher = pattern.matcher(phone);
        
       if(!(matcher.find()))
       {
           phone_no.setForeground(Color.RED);
       }
       else
       {
           if( phone.length()<10 || phone.length()>10)
           {
               phone_no.setForeground(Color.RED);
           }
           else
           {
           phone_no.setForeground(Color.BLUE);
           }
       }
    }//GEN-LAST:event_phone_noKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox branch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox city;
    private javax.swing.JComboBox college;
    private javax.swing.JComboBox country;
    private javax.swing.JComboBox date;
    private javax.swing.JComboBox department;
    private javax.swing.JTextField email_id;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField first_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField last_name;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox month;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone_no;
    private javax.swing.JButton register;
    private javax.swing.JPasswordField retype_password;
    private javax.swing.JFormattedTextField roll_no;
    private javax.swing.JLabel staff_label;
    private javax.swing.JTextField staff_year;
    private javax.swing.JLabel student_label;
    private javax.swing.JComboBox student_year;
    private javax.swing.JComboBox type;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
}
